"""test_agents_md_no_superseded_terms.py — T-PR14-004, R21 final repo-wide gate.

Req: R21 · Design: §15 · Depends on: T-PR14-003, T-PR9-007

Repo-wide grep for the withdrawn D1-original vocabulary (design.md §0
amendment log #1, D1-rev): a document numbered ``consecutivo_actual`` in
the cloud, a preliminary/official split (``numero_temporal`` /
``numero_oficial``), and the invented ``sync_back_event`` /
``SyncBackEvent`` provider-notification-push mechanism. ``AGENTS.md`` is
read as canon by every future agent (T-PR9-007's own docstring: "This is
how the original defect propagated") — this test is the FULL repo-wide
gate PR9's own early check (``test_no_sync_back_event_literals.py``,
scoped to 2 files) explicitly deferred to PR14.

**Every occurrence outside a marked exception below is a violation.**
Nothing here is scanned for "reasonable-sounding" negation phrasing —
each allowed occurrence is an EXPLICIT, individually-justified entry, so a
new file introducing this vocabulary always fails closed.

**Exceptions, and why each one is not a violation:**

  - ``AGENTS.md`` itself keeps exactly ONE sentence using
    ``consecutivo_actual`` — the T-PR14-003 replacement text, which
    states the column was REMOVED ("``empresa`` has no
    ``consecutivo_actual`` column (removed in the 4NF pass)"). This is
    matched by EXACT line content, not merely "contains the word" — any
    OTHER line in ``AGENTS.md`` referencing the withdrawn vocabulary still
    fails this test.
  - ``modelo_datos_er.mmd`` (canonical ER) carries one ``%%`` Mermaid
    comment noting ``consecutivo_actual`` was eliminated in the 4NF pass —
    the same negation as AGENTS.md's own correction, on the immutable
    source-of-truth file.
  - ``sync/catalog/schema.py``'s "Fields removed by this amendment"
    docstring documents that ``sync_back_event`` was a REMOVED
    ``SyncCatalogEntry`` field (D1-rev) — the same amendment-log
    convention ``design.md``'s own §0 uses throughout.
  - ``sync/catalog/entries/sync_entries_{le,lw,a}.py`` document, in
    negation form, that ``sync_back_event`` (a per-row flag) and
    ``sync_back_events`` (a table) do NOT exist / were withdrawn — never a
    re-assertion that they exist.
  - ``tests/unit/test_catalog_schema.py`` asserts ``sync_back_event`` was
    REMOVED from ``SyncCatalogEntry``'s field set (PR2's own guard).
  - ``tests/static/test_no_sync_back_event_literals.py`` is PR9's own
    early guard (T-PR9-007) — it parametrizes on these EXACT literals as
    search DATA to assert their absence from 2 specific files. This test
    supersedes it in coverage; it must not be double-flagged for using
    its own search terms.
  - ``sync/cutover/stage_runner.py`` is THIS CHANGE's own stage-2 gate
    (T-PR14-001) — it reads ``operacion='sync_back_event'`` as a literal
    DB value to verify NO such row exists anywhere (D1-rev/R21). A guard
    reading the forbidden literal as check DATA is not a re-assertion of
    the withdrawn model.
  - ``backend/scripts/replicate_catalogs_to_branch.py`` is one of the 4
    untracked legacy demo scripts proposal §9.6 explicitly says to leave
    untouched ("Not part of this deliverable").
  - This test's OWN file is self-excluded — ``_FORBIDDEN_LITERALS`` below
    necessarily contains these literals as search DATA; scanning this
    file for its own search terms would be the exact tautological trap a
    PR11 agent hit with its own prohibited-literal docstring.

Heavy/irrelevant trees (``.git``, ``.venv``, ``__pycache__``,
``.pytest_cache``, ``.ruff_cache``, ``.codegraph``, ``node_modules``,
``.agent-generated``) and generated OpenAPI snapshots (``openapi.json`` —
stale build artifacts from ``create-49-table-apis``, never regenerated by
any ``sync-overhaul`` PR; a documented, out-of-scope gap, not fixed here)
are pruned. ``openspec/changes/**`` and ``openspec/_meta/**`` (SDD
historical/decision/planning artifacts across EVERY change, not just this
one) are pruned too — they inherently describe the withdrawn model to
explain why it was replaced; R21's concern is ``AGENTS.md`` re-deriving
from stale CANON, not dated decision records. ``openspec/scripts/**``
stays IN SCOPE (live operational code).
"""
from __future__ import annotations

import os
from pathlib import Path

_THIS_FILE = Path(__file__).resolve()
_REPO_ROOT = _THIS_FILE.parents[3]

_FORBIDDEN_LITERALS: tuple[str, ...] = (
    "consecutivo_actual",
    "numero_temporal",
    "numero_oficial",
    "sync_back_event",
    "SyncBackEvent",
)

_EXCLUDED_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "__pycache__",
        ".pytest_cache",
        ".ruff_cache",
        ".codegraph",
        "node_modules",
        ".agent-generated",
        ".atl",
        ".claude",
        ".github",
    }
)

# Relative-to-repo-root path prefixes pruned wholesale (POSIX separators).
_EXCLUDED_RELATIVE_PREFIXES: tuple[str, ...] = (
    "openspec/changes",
    "openspec/_meta",
)

_EXCLUDED_FILENAMES: frozenset[str] = frozenset({"openapi.json"})

_AGENTS_MD_RELATIVE = "AGENTS.md"
_AGENTS_MD_ALLOWED_LINE = (
    "- **Invoice numbering is branch-local**: `consecutivo` is assigned at the branch "
    "inside its own `resolucion_facturacion` range (`rango_desde`/`rango_hasta`); "
    "uniqueness comes from UK `(uuid_resolucion_facturacion, consecutivo)`. `empresa` "
    "has no `consecutivo_actual` column (removed in the 4NF pass)."
)

# Whole-file exceptions (relative-to-repo-root, POSIX separators) — see the
# module docstring for the justification of each entry.
_ALLOWED_FILES_RELATIVE: frozenset[str] = frozenset(
    {
        "modelo_datos_er.mmd",
        "backend/packages/parkos_core/src/parkos_core/sync/catalog/schema.py",
        "backend/packages/parkos_core/src/parkos_core/sync/catalog/entries/sync_entries_le.py",
        "backend/packages/parkos_core/src/parkos_core/sync/catalog/entries/sync_entries_lw.py",
        "backend/packages/parkos_core/src/parkos_core/sync/catalog/entries/sync_entries_a.py",
        "backend/tests/unit/test_catalog_schema.py",
        "backend/tests/static/test_no_sync_back_event_literals.py",
        "backend/packages/parkos_core/src/parkos_core/sync/cutover/stage_runner.py",
        "backend/scripts/replicate_catalogs_to_branch.py",
        # T-PR14-002 / T-PR14-005 tests seed the forbidden literal as DATA to
        # exercise a guard, exactly like stage_runner.py's own gate above.
        "backend/tests/unit/test_stage_runner.py",
        "backend/tests/integration/test_reverse_dry_run.py",
    }
)


def _iter_repo_files(repo_root: Path) -> list[Path]:
    files: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        current = Path(dirpath)
        rel = current.relative_to(repo_root).as_posix()

        pruned: list[str] = []
        for d in dirnames:
            if d in _EXCLUDED_DIR_NAMES:
                continue
            child_rel = d if rel == "." else f"{rel}/{d}"
            if any(
                child_rel == prefix or child_rel.startswith(prefix + "/")
                for prefix in _EXCLUDED_RELATIVE_PREFIXES
            ):
                continue
            pruned.append(d)
        dirnames[:] = pruned

        for fname in filenames:
            if fname in _EXCLUDED_FILENAMES:
                continue
            files.append(current / fname)
    return files


def _read_text_or_none(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def test_no_superseded_terms_outside_marked_blocks() -> None:
    violations: list[str] = []

    for path in _iter_repo_files(_REPO_ROOT):
        if path == _THIS_FILE:
            continue

        rel = path.relative_to(_REPO_ROOT).as_posix()
        source = _read_text_or_none(path)
        if source is None:
            continue

        if rel == _AGENTS_MD_RELATIVE:
            for lineno, line in enumerate(source.splitlines(), start=1):
                if (
                    any(term in line for term in _FORBIDDEN_LITERALS)
                    and line.strip() != _AGENTS_MD_ALLOWED_LINE
                ):
                    violations.append(f"{rel}:{lineno}: {line.strip()!r}")
            continue

        if rel in _ALLOWED_FILES_RELATIVE:
            continue

        for lineno, line in enumerate(source.splitlines(), start=1):
            for term in _FORBIDDEN_LITERALS:
                if term in line:
                    violations.append(f"{rel}:{lineno}: contains {term!r} — {line.strip()!r}")

    assert not violations, (
        f"{len(violations)} superseded-term violation(s) found outside marked exceptions "
        "(R21, D1-rev):\n" + "\n".join(violations)
    )
